name: farmer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-214.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.0+2
  file_picker: ^8.0.7
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localization: ^0.2.1
  flutter_map: ^7.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl_utils: ^2.8.7
  latlong2: ^0.9.1
  linear_progress_bar: ^1.1.2
  otp: ^3.1.4
  webview_flutter: ^4.8.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  geolocator: ^8.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons_assets/
    - assets/gif/audio.gif
  generate: true
  # Specify the directory where your .arb files are located
  
    