name: farmer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-214.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.0+2
  file_picker: ^8.0.7
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl_utils: ^2.8.7
  linear_progress_bar: ^1.1.2
  otp: ^3.1.4
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  generate: true
  # Specify the directory where your .arb files are located
  
    