// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOLiVYfZePZoEXLosJE3drnGCNelCyTxI',
    appId: '1:52694940780:web:632fd1d55d3170b1ec6c49',
    messagingSenderId: '52694940780',
    projectId: 'sih-backend-7be13',
    authDomain: 'sih-backend-7be13.firebaseapp.com',
    storageBucket: 'sih-backend-7be13.appspot.com',
    measurementId: 'G-BSNV41N7QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaglh5C40c8uZ3OJBfwVLyohy1SwJMNus',
    appId: '1:52694940780:android:9e33559e98eb4ca6ec6c49',
    messagingSenderId: '52694940780',
    projectId: 'sih-backend-7be13',
    storageBucket: 'sih-backend-7be13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeY0a_VrQGvlYMzCWPhYqKcfmXBciTldU',
    appId: '1:52694940780:ios:d5a9894609caebdfec6c49',
    messagingSenderId: '52694940780',
    projectId: 'sih-backend-7be13',
    storageBucket: 'sih-backend-7be13.appspot.com',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeY0a_VrQGvlYMzCWPhYqKcfmXBciTldU',
    appId: '1:52694940780:ios:30afd9e05134a977ec6c49',
    messagingSenderId: '52694940780',
    projectId: 'sih-backend-7be13',
    storageBucket: 'sih-backend-7be13.appspot.com',
    iosBundleId: 'com.example.farmerApp.RunnerTests',
  );
}
